version: '3.8'
services:
  api:
    build:
      context: .
    image: api
    container_name: estore-api
    restart: always
    command: npm run start:prod
    ports:
      - 3002:3002
    volumes:
      - ./:/app/src:ro
    environment:
      PORT:
      NODE_ENV:
      TZ:
      LOG_LEVEL:
      SWAGGER_USER:
      SWAGGER_PASSWORD:
      API_KEY:

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}']
      retries: 3
      interval: 60s
      timeout: 10s
      start_period: 40s
