import { EXAMPLES } from '@ukef/constants';

import { ValidatedStringApiProperty } from './validated-string-api-property.decorator';

interface Options {
  description: string;
}

// The site identifier is usually generated by the number generator (as in the POST /sites endpoint)
// but sometimes it is set manually, in which case it can be any string with at least one character.
export const ValidatedSiteIdentifierApiProperty = ({ description }: Options) =>
  ValidatedStringApiProperty({
    description,
    minLength: 1,
    example: EXAMPLES.SITE_ID,
  });
