import { EXAMPLES, SHAREPOINT } from '@ukef/constants';

import { ValidatedStringApiProperty } from './validated-string-api-property.decorator';

interface Options {
  description: string;
}

// The site identifier is usually generated by the number generator (as in the POST /sites endpoint)
// but sometimes it is set manually, in which case it can be a string with at least one character
// and does not use the following invalid characters ,&!@~#$%*:;()+./\[]- .
export const ValidatedSiteIdentifierApiProperty = ({ description }: Options) =>
  ValidatedStringApiProperty({
    description,
    minLength: 1,
    pattern: SHAREPOINT.CASE_SITE_URL.REGEX,
    example: EXAMPLES.SITE_ID,
  });
