# This GHA is responsible for APIM deployment.
# Deployment is initiated using `az cli` bash script.
#
# Standard Azure naming convention has been followed:
# https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming
#
#
# Following Azure services are consumed:
# 1. Azure resource group - https://learn.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create
# 2. Azure container registry - https://learn.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-create
# 3. Azure container app environment - https://learn.microsoft.com/en-us/azure/container-apps/environment
# 4. Azure container app - https://learn.microsoft.com/en-us/azure/container-apps/containers
#
#
# Execution
# *********
# GHA is only invoked when following conditions are satisfied:
# 1. Push to the `dev`, `staging` and `production` branches only.
# 2. Any modifications to atleast one of the `paths` targets.

name: Deployment 🚀
run-name: APIM deployment for ${{ github.repository }}

on:
  push:
    branches:
      - dev
      - staging
      - production

    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - ".github/workflows/deployment.yml"

env:
  PRODUCT: apim
  ENVIRONMENT: ${{ github.ref_name }}
  TIMEZONE: "Europe/London"
  # Base artifact
  FROM: latest

jobs:
  # 1. Setup deployment variables
  setup:
    name: Setup 🔧
    runs-on: [self-hosted, deployment]
    outputs:
      product: ${{ env.PRODUCT }}
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.ENVIRONMENT }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.TIMEZONE }}"

  # 2. eStore micro-service deployment
  estore:
    name: eStore 📦️
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      NAME: estore
      NAME_UPPERCASE: ESTORE
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    runs-on: [self-hosted, deployment]
    steps:
      - name: Repository 🗃️
        uses: actions/checkout@v3

      - name: Azure 🔐
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Defaults ✨
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # Basic
            az configure --defaults location=${{ vars.REGION }}
            az configure --defaults group=rg-${{ env.PRODUCT }}-${{ github.ref_name }}-${{ vars.VERSION }}

      - name: CLI 📝
        run: |
          echo ACR=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query loginServer -o tsv) >> $GITHUB_ENV
          echo ACR_USER=$(az acr show -n $(az resource list --resource-type 'Microsoft.ContainerRegistry/registries' --query '[0].name' -o tsv) --query name -o tsv) >> $GITHUB_ENV
          echo CA_NAME=$(az resource list --resource-type 'Microsoft.App/containerApps' --query '[?contains(name, `${{ env.NAME }}`)].name' -o tsv) >> $GITHUB_ENV
          echo APIM=$(az resource list --resource-type 'Microsoft.ApiManagement/service' --query '[0].name' -o tsv) >> $GITHUB_ENV
          echo API_ID=$(az apim api list --service-name $(az resource list --resource-type 'Microsoft.ApiManagement/service' --query '[0].name' -o tsv) --query '[?contains(displayName, `${{ env.NAME_UPPERCASE }}`)].name' -o tsv) >> $GITHUB_ENV

      - name: ACR 🔐
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR }}
          username: ${{ env.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Artifacts 🗃️
        run: |
          docker build . \
          -t ${{ env.ACR }}/${{ env.NAME }}:${{ github.sha }} \
          -t ${{ env.ACR }}/${{ env.NAME }}:${{ env.FROM }}
          docker push ${{ env.ACR }}/${{ env.NAME }}:${{ github.sha }}
          docker push ${{ env.ACR }}/${{ env.NAME }}:${{ env.FROM }}

      - name: Revisions 🔀
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az containerapp update \
            --name ${{ env.CA_NAME }} \
            --container-name ${{ env.CA_NAME }} \
            --image ${{ env.ACR }}/${{ env.NAME }}:${{ env.FROM }} \
            --revision-suffix v${{ github.run_id }} \
            --set-env-vars \
            "PORT=${{ secrets.PORT }}" \
            "NODE_ENV=${{ secrets.NODE_ENV }}" \
            "TZ=${{ secrets.TZ }}" \
            "LOG_LEVEL=${{ vars.LOG_LEVEL }}" \
            "REDACT_LOGS=${{ vars.REDACT_LOGS }}" \
            "SINGLE_LINE_LOG_FORMAT=${{ vars.SINGLE_LINE_LOG_FORMAT }}" \
            "SWAGGER_USER=${{ secrets.SWAGGER_USER }}" \
            "SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }}" \
            "API_KEY=${{ secrets.API_KEY }}" \
            "GRAPH_BASE_URL=${{ secrets.GRAPH_BASE_URL }}" \
            "GRAPH_AUTHENTICATION_TENANT_ID=${{ secrets.GRAPH_AUTHENTICATION_TENANT_ID }}" \
            "GRAPH_AUTHENTICATION_CLIENT_ID=${{ secrets.GRAPH_AUTHENTICATION_CLIENT_ID }}" \
            "GRAPH_AUTHENTICATION_CLIENT_SECRET=${{ secrets.GRAPH_AUTHENTICATION_CLIENT_SECRET }}" \
            "SHAREPOINT_BASE_URL=${{ secrets.SHAREPOINT_BASE_URL }}" \
            "SHAREPOINT_MAIN_SITE_NAME=${{ secrets.SHAREPOINT_MAIN_SITE_NAME }}" \
            "SHAREPOINT_TFIS_SITE_NAME=${{ secrets.SHAREPOINT_TFIS_SITE_NAME }}" \
            "SHAREPOINT_SC_SITE_NAME=${{ secrets.SHAREPOINT_SC_SITE_NAME }}" \
            "SHAREPOINT_SC_CASE_SITES_LIST_ID=${{ secrets.SHAREPOINT_SC_CASE_SITES_LIST_ID }}" \
            "SHAREPOINT_TFIS_FACILITY_LIST_ID=${{ secrets.SHAREPOINT_TFIS_FACILITY_LIST_ID }}" \
            "SHAREPOINT_TFIS_FACILITY_HIDDEN_LIST_TERM_STORE_ID=${{ secrets.SHAREPOINT_TFIS_FACILITY_HIDDEN_LIST_TERM_STORE_ID }}" \
            "SHAREPOINT_TFIS_SITE_ID=${{ secrets.SHAREPOINT_TFIS_SITE_ID }}" \
            "SHAREPOINT_TFIS_DEAL_LIST_ID=${{ secrets.SHAREPOINT_TFIS_DEAL_LIST_ID }}" \
            "SHAREPOINT_TFIS_TERM_STORE=${{ secrets.SHAREPOINT_TFIS_TERM_STORE }}" \
            "SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_FIELD_NAME=${{ secrets.SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_FIELD_NAME }}" \
            "SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_APPLICATION=${{ secrets.SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_APPLICATION }}" \
            "SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_FINANCIAL_STATEMENT=${{ secrets.SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_FINANCIAL_STATEMENT }}" \
            "SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_BUSINESS_INFORMATION=${{ secrets.SHAREPOINT_ESTORE_DOCUMENT_TYPE_ID_BUSINESS_INFORMATION }}" \
            "SHAREPOINT_TFIS_CASE_SITES_LIST_ID=${{ secrets.SHAREPOINT_TFIS_CASE_SITES_LIST_ID }}" \
            "SHAREPOINT_TAXONOMY_HIDDEN_LIST_TERM_STORE_LIST_ID=${{ secrets.SHAREPOINT_TAXONOMY_HIDDEN_LIST_TERM_STORE_LIST_ID }}" \
            "SHAREPOINT_ECMS_DOCUMENT_CONTENT_TYPE_ID=${{ secrets.SHAREPOINT_ECMS_DOCUMENT_CONTENT_TYPE_ID }}" \
            "APIM_MDM_URL=${{ secrets.APIM_MDM_URL }}" \
            "APIM_MDM_KEY=${{ secrets.APIM_MDM_KEY }}" \
            "APIM_MDM_VALUE=${{ secrets.APIM_MDM_VALUE }}" \
            "APIM_MDM_MAX_REDIRECTS=${{ secrets.APIM_MDM_MAX_REDIRECTS }}" \
            "APIM_MDM_TIMEOUT=${{ secrets.APIM_MDM_TIMEOUT }}" \
            "DTFS_STORAGE_ACCOUNT_NAME=${{ secrets.DTFS_STORAGE_ACCOUNT_NAME }}" \
            "DTFS_STORAGE_ACCOUNT_KEY=${{ secrets.DTFS_STORAGE_ACCOUNT_KEY }}" \
            "DTFS_STORAGE_DEAL_DOCUMENTS_FOLDER_PATH=${{ secrets.DTFS_STORAGE_DEAL_DOCUMENTS_FOLDER_PATH }}" \
            "DTFS_STORAGE_EXAMPLE_FILE_NAME=${{ secrets.DTFS_STORAGE_EXAMPLE_FILE_NAME }}" \
            "DTFS_STORAGE_EXAMPLE_FILE_LOCATION_PATH=${{ secrets.DTFS_STORAGE_EXAMPLE_FILE_LOCATION_PATH }}" \
            "CUSTODIAN_BASE_URL=${{ secrets.CUSTODIAN_BASE_URL }}" \
            "CUSTODIAN_API_KEY_HEADER_NAME=${{ secrets.CUSTODIAN_API_KEY_HEADER_NAME }}" \
            "CUSTODIAN_API_KEY_HEADER_VALUE=${{ secrets.CUSTODIAN_API_KEY_HEADER_VALUE }}" \
            "CUSTODIAN_MAX_REDIRECTS=${{ secrets.CUSTODIAN_MAX_REDIRECTS }}" \
            "CUSTODIAN_TIMEOUT=${{ secrets.CUSTODIAN_TIMEOUT }}" \
            "CUSTODIAN_BUYER_TEMPLATE_ID=${{ secrets.CUSTODIAN_BUYER_TEMPLATE_ID }}" \
            "CUSTODIAN_BUYER_TYPE_GUID=${{ secrets.CUSTODIAN_BUYER_TYPE_GUID }}" \
            "CUSTODIAN_DEAL_TEMPLATE_ID=${{ secrets.CUSTODIAN_DEAL_TEMPLATE_ID }}" \
            "CUSTODIAN_DEAL_TYPE_GUID=${{ secrets.CUSTODIAN_DEAL_TYPE_GUID }}" \
            "CUSTODIAN_FACILITY_TEMPLATE_ID=${{ secrets.CUSTODIAN_FACILITY_TEMPLATE_ID }}" \
            "CUSTODIAN_FACILITY_TYPE_GUID=${{ secrets.CUSTODIAN_FACILITY_TYPE_GUID }}"

      - name: Import ⬇️
        if: ${{ '' != env.API_ID }}
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # API specification import

            az apim api import \
            --path '${{ env.NAME }}' \
            --service-name ${{ env.APIM }} \
            --specification-format OpenApi \
            --api-id ${{ env.API_ID }} \
            --api-type http \
            --service-url https://$(az containerapp show --name ${{ env.CA_NAME }} --query properties.latestRevisionFqdn -o tsv) \
            --protocols https \
            --specification-url https://$(az containerapp show --name ${{ env.CA_NAME }} --query properties.latestRevisionFqdn -o tsv)/openapi/json \
            --subscription-required true
