# This GHA is responsible for `APIM` (eStore) supporting infrastructure
# creation and configuration using `az cli` bash scripting.
#
# The workflow consists of two jobs:
# * `setup`
# * `base`
#
# The setup job sets up environment variables by defining the product, environment, timezone, and target variables.
# It then sets the output variables environment and timezone, which are used by the base job.
#
# The base job creates the base infrastructure required for an APIM deployment.
# It sets up Azure CLI extensions and uses the Azure CLI to create the following resources:
#
#
# The workflow also sets various environment tags and prints out the state of the VNET peering connection.
# Finally, note that some variables, such as `REGION`, `VERSION`, and various Azure credentials are defined as env variables or secrets respectively.
#
# Standard Azure naming convention has been followed:
# https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming
# A minor modification to standard naming convention has been made to not include region.
#
#
# Following Azure services are consumed:
# 1. Azure resource group - https://learn.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create
# 2. Azure container registry - https://learn.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-create
# 3. Azure container app environment - https://learn.microsoft.com/en-us/azure/container-apps/environment
# 4. Azure container app - https://learn.microsoft.com/en-us/azure/container-apps/containers
# 5. Azure API management - https://learn.microsoft.com/en-us/azure/api-management/
# 6. Azure log analytics workspace - https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-workspace-overview
#
#
# Execution
# *********
# GHA is only invoked when following conditions are satisfied:
# 1. Push to the `infrastructure` branch only.
# 2. Exact file path matches `.github/workflows/infrastructure.yml`.
#
# Flow
# ****
# eStore (https://github.com/UK-Export-Finance/estore-api) infrastructure.yml will be executed prior to
# eStore `infrastructure.yml` execution. Despite majority of the base infrastructure already being in
# place (due to eStore execution) base infrastructure has been kept in place for an independent eStore
# deployment scenarios.
#
# Azure CLI will merely ignore the new resource creation if already exist with same name.
#
# NOTE
# ****
#
# 1. APIM Policy
# --------------
# AZ CLI currently do not support APIM policy import natively, recommended solution is via
# `az rest` https://github.com/Azure/azure-cli/issues/14695
#

name: Infrastructure 🔨
run-name: APIM base infrastructure build from ${{ github.repository }}

on:
  push:
    branches:
      - infrastructure

    paths: [.github/workflows/infrastructure.yml]

env:
  PRODUCT: apim
  ENVIRONMENT: infrastructure
  TIMEZONE: "Europe/London"
  # Deployment environment target i.e., `dev`, `staging`, `production`
  TARGET: ${{ vars.ENVIRONMENT }}

jobs:
  # 1. Setup infrastructure variables
  setup:
    name: Setup 🔧
    runs-on: [self-hosted, infrastructure]
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.ENVIRONMENT }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.TIMEZONE }}"

  # 2. Base infrastructure creation
  base:
    name: Base 🧱
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    outputs:
      environment: ${{ env.ENVIRONMENT }}
    runs-on: [self-hosted, infrastructure]
    steps:
      - name: Pre-production 💫
        if: contains('["dev", "staging"]', env.TARGET)
        run: echo "TYPE=Preproduction" >> $GITHUB_ENV

      - name: Production 💫
        if: ${{ 'production' == env.TARGET }}
        run: echo "TYPE=Production" >> $GITHUB_ENV

      - name: Tags 🏷️
        run: echo TAGS='Environment=${{ env.TYPE }}' \
          'Product=${{ env.PRODUCT }}' \
          'Team=development' >> $GITHUB_ENV

      - name: Login 🔐
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure defaults ✨
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # Basic
            az configure --defaults location=${{ vars.REGION }}
            az configure --defaults group=rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}

            # AZ CLI extensions upgrade
            az extension add --name containerapp --upgrade

      - name: Resource group 🏗️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az group create \
            --name rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --tags ${{ env.TAGS }}

      - name: Log analytics workspace 📝
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az monitor log-analytics workspace create \
            --name log-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --capacity-reservation-level 100 \
            --ingestion-access Disabled \
            --query-access Disabled \
            --quota 0.05 \
            --retention-time ${{ vars.LOG_RETENTION_DAY }} \
            --sku ${{ vars.LOG_PLAN }} \
            --tags ${{ env.TAGS }}

      - name: Container registry 📦️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az acr create \
            --name cr${{ env.PRODUCT }}${{ env.TARGET }}${{ vars.VERSION }} \
            --sku ${{ vars.ACR_PLAN }} \
            --admin-enabled true \
            --workspace log-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --tags ${{ env.TAGS }}

      - name: Container app environment 🗃️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az containerapp env create \
            --name cae-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --infrastructure-subnet-resource-id $(az network vnet subnet show --name snet-${{ env.PRODUCT }}-${{ vars.VERSION }} --vnet-name vnet-${{ env.PRODUCT }}-${{ vars.VERSION }} --query 'id' -o tsv) \
            --logs-workspace-id $(az monitor log-analytics workspace show --name log-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query customerId -o tsv) \
            --logs-workspace-key $(az monitor log-analytics workspace get-shared-keys --name log-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query primarySharedKey -o tsv) \
            --tags ${{ env.TAGS }}

      - name: Container app - eStore 📄
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az containerapp create \
            --name ca-${{ env.PRODUCT }}-estore-${{ env.TARGET }}-${{ vars.VERSION }} \
            --environment cae-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --registry-server cr${{ env.PRODUCT }}${{ env.TARGET }}${{ vars.VERSION }}.azurecr.io \
            --registry-username $(az acr credential show -n cr${{ env.PRODUCT }}${{ env.TARGET }}${{ vars.VERSION }} --query username -o tsv) \
            --cpu 1.0 \
            --memory 2.0Gi \
            --min-replicas 1 \
            --max-replicas 4 \
            --ingress external \
            --target-port ${{ vars.PORT }} \
            --revisions-mode multiple \
            --transport auto \
            --tags ${{ env.TAGS }}

      - name: API management ⚡️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az apim create \
            --name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --publisher-email ${{ secrets.NOTIFICATION }} \
            --publisher-name UKEF \
            --public-network-access true \
            --sku-capacity 1 \
            --sku-name ${{ vars.APIM_PLAN }} \
            --tags ${{ env.TAGS }}

  # 3. Container app configuration
  ca:
    name: Container app 🔧
    needs: base
    environment: ${{ needs.base.outputs.environment }}
    runs-on: [self-hosted, infrastructure]
    steps:
      - name: Pre-production 💫
        if: contains('["dev", "staging"]', env.TARGET)
        run: echo "TYPE=Preproduction" >> $GITHUB_ENV

      - name: Production 💫
        if: ${{ 'production' == env.TARGET }}
        run: echo "TYPE=Production" >> $GITHUB_ENV

      - name: Login 🔐
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure defaults ✨
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # Basic
            az configure --defaults location=${{ vars.REGION }}
            az configure --defaults group=rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}

      - name: APIM defaults ✨
        run: |
          echo PRODUCT_STARTER=$(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `Starter`)].name' -o tsv) >> $GITHUB_ENV
          echo PRODUCT_UNLIMITED=$(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `Unlimited`)].name' -o tsv) >> $GITHUB_ENV
          echo API_ECHO=$(az apim api list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --filter-display-name 'Echo API' --top 1 --query [0].name -o tsv) >> $GITHUB_ENV

      - name: IP restriction 🔒️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # Add APIM public IP

            # eStore
            az containerapp ingress access-restriction set \
            --name ca-${{ env.PRODUCT }}-estore-${{ env.TARGET }}-${{ vars.VERSION }} \
            --action Allow \
            --ip-address $(az apim show --name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query publicIpAddresses -o tsv) \
            --rule-name APIM \
            --description 'Allow APIM public IP address'

      - name: Delete - Starter product
        uses: Azure/cli@v1.0.7
        if: ${{ '' != env.PRODUCT_STARTER }}
        with:
          inlineScript: |
            az apim product delete \
            --product-id $(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `Starter`)].name' -o tsv) \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --delete-subscriptions true \
            --yes

      - name: Delete - Unlimited product
        uses: Azure/cli@v1.0.7
        if: ${{ '' != env.PRODUCT_UNLIMITED }}
        with:
          inlineScript: |
            az apim product delete \
            --product-id $(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `Unlimited`)].name' -o tsv) \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --delete-subscriptions true \
            --yes

      - name: Delete - Echo API
        uses: Azure/cli@v1.0.7
        if: ${{ '' != env.API_ECHO }}
        with:
          inlineScript: |
            az apim api delete \
            --api-id $(az apim api list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --filter-display-name 'Echo API' --top 1 --query [0].name -o tsv) \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --delete-revisions true \
            --yes

  # 5. APIM configuration
  apim:
    name: API management 🔧
    needs: base
    environment: ${{ needs.base.outputs.environment }}
    runs-on: [self-hosted, infrastructure]
    steps:
      - name: Pre-production 💫
        if: contains('["dev", "staging"]', env.TARGET)
        run: echo "TYPE=Preproduction" >> $GITHUB_ENV

      - name: Production 💫
        if: ${{ 'production' == env.TARGET }}
        run: echo "TYPE=Production" >> $GITHUB_ENV

      - name: Login 🔐
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure defaults ✨
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            # Basic
            az configure --defaults location=${{ vars.REGION }}
            az configure --defaults group=rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}

      - name: APIM defaults ✨
        run: |
          echo PRODUCT_ESTORE=$(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `estore`)].name' -o tsv) >> $GITHUB_ENV

      - name: eStore - Product ➕
        uses: Azure/cli@v1.0.7
        if: ${{ '' == env.PRODUCT_ESTORE }}
        with:
          inlineScript: |
            az apim product create \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --product-name apim-${{ env.PRODUCT }}-estore \
            --description '${{ vars.DESCRIPTION }}' \
            --state published \
            --approval-required true \
            --subscription-required true

      - name: eStore - API import ⬇️
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az apim api import \
            --display-name 'ESTORE' \
            --description '${{ vars.DESCRIPTION }}' \
            --service-url https://$(az containerapp show --name ca-${{ env.PRODUCT }}-estore-${{ env.TARGET }}-${{ vars.VERSION }} --query properties.latestRevisionFqdn -o tsv) \
            --path 'estore' \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --specification-format OpenApi \
            --api-type http \
            --protocols https \
            --subscription-required true \
            --specification-url https://$(az containerapp show --name ca-${{ env.PRODUCT }}-estore-${{ env.TARGET }}-${{ vars.VERSION }} --query properties.latestRevisionFqdn -o tsv)/openapi/json

      - name: eStore - Product + API 🧱
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az apim product api add \
            --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} \
            --api-id $(az apim api list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --filter-display-name 'ESTORE' --top 1 --query [0].name -o tsv) \
            --product-id $(az apim product list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --query '[?contains(displayName, `apim-${{ env.PRODUCT }}-estore`)].name' -o tsv)

      - name: eStore - Policy 🚧
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az rest \
            --method PUT \
            --uri "https://management.azure.com/subscriptions/$(az account show --query id -o tsv)/resourceGroups/rg-${{ env.PRODUCT }}-${{ env.TARGET }}-${{ vars.VERSION }}/providers/Microsoft.ApiManagement/service/apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }}/apis/$(az apim api list --service-name apim-${{ env.ENVIRONMENT }}-${{ env.TARGET }}-${{ vars.VERSION }} --filter-display-name 'ESTORE' --top 1 --query [0].name -o tsv)/policies/policy?api-version=2022-09-01-preview" \
            --body ${{ secrets.APIM_POLICY }}
